project:
  type: website
  output-dir: docs

website:
  title: "Moving quietly and planting things"
  site-url: https://movequietly.eu
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  cookie-consent: false      
format:
  html:
    theme: flatly
    css: styles.css
    mainfont: arial

lang: cs



