project:
  type: website
  output-dir: docs

website:
  title: "Move quietly and plant things"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  cookie-consent: false      
format:
  html:
    theme: flatly
    css: styles.css
    mainfont: arial

lang: cs



