---
title: "Poznatky z lekce Ido Portal Method"
author: "Edgar Walden"
date: "2022-04-14"
categories: [pohyb, as time goes by]
image: ""
filters:
   - lightbox
lightbox: auto
---

Konečně se mi povedlo dostat se na lekci pohybu Ido Portal Method a byla výborná. Hodně nových podnětů pro mou praxi i sádhanu. 

Movement culture tu více tu méně obdivuju už poměrně dlouho. Pokud nevíte, co to je, googlujte hlavně jejího zakladatele **Ido Portala**. Ido Portal je Izraelec, který před lety začínal s capoeirou, ale poté vyvinul vlastní systém pohybu. Je to docela hustej týpek, který okolo sebe (možná schválně, možná ne) šíří takovou trochu tajemnou auru. Zabývá se pohybem a umí se hýbat naprosto skvěle. Když říkám "zabývá se pohybem", tak jako že opravdu. Cestuje po světě a vstřebáývá různé systémy (nebo to aspoň dřív dělal) cvičí v podstatě nepřetržitě a hlavně o pohybu také přemýšlí. 

Jeho koncepce zahrnuje spoustu věcí - silové cviky s vlastní vahou, lokomoce, prvky z jógy (hodně integruje Shadow Yogu Sandora Remete), moderního tance a bůhví čeho ještě. Výsledkem je systém pohybových technik, který vede k jakémusi univerzálnímu rozvoji pohybových schopností. No a na jednu otevřenou lekci **Ido Portal Method** ve Zlíně se mi podařilo zajet. A výsledek? Spousta inspirace a podnětů k pohybu i přemýšlení.

Při přihlašování na otevřenou lekci jsem udělal jednu chybu - lekce byly v jeden den dvě s různými učiteli. Myslel, že jsou stejné, ale nebyly a kdybych to byl věděl, navštívil bych obě. Takto jsem byl jen na jedné - odpolední. Poučení pro příště. Lekce měla nějaké dvě a půl nebo tři hodiny - uteklo to jako voda, klidně bych cvičil ještě dál.

## Hra, euforie, bolavé kosti

Začínalo se dvěma pohybovými hrami ve dvojici. Zvláště druhá z nich mi připomněla tréningy Aikida, měli jsme jakoukoli částí těla naznačit "útok" a partner se měl tomu pohybu vyhnout a na "útočící" část těla udělat protiútok. Je to taková zápasnická hra, ale v podstatě bez kontaktu, trochu mi to připomínalo třeba **přetlačováni rukama** v Taj-chi. No a to Aikido - prostě jsem ze začátku musel přemáhat reflex chytnout na útočící ruku a udělat nějakou páku. I po těch letech to funguje :-). Každopádně jsem se pár lidma při této hře dostal do pěkného pohybového flow.

No a pak jsme zkoušeli různé pohyby na zemi. Pohyby s názvy "Down the sink" nebo "S-wheel", vše jsem si dával do poznámek, že to později vygoogluju, ale marně. Jde asi o interní názvy Ido Portal Method a na netu k nim informace nejsou. Možná to také byly jen ad-hoc vymyšlené názvy. Celá IPM je totiž zaměřena hodně na praxi a od informací na netu si IMHO drží trochu odstup. 

A jak to na mě celé působilo? O drsném cvičení na Movement Campech se vedou legendy, tady to bylo poměrně krotké. Víc než svaly se mi namáhal mozek, i když jsem pak cítil celé tělo. Libilo se mi, že lekce byla hodně hravá, obtížné části prokládalo házení s tenisáky. V podstatě se dá říct, že jsem se hlavně u těžších částí pohybu na zemi moc "nechytal", ale to v podstatě nikdo. Každopádně jsem měl ze cvičení hodně dobrou, až skoro povznesenou a euforickou náladu - mohl za to ale samozřejmě také příjemný instruktor. Na závěr mě úplně překvapilo, že už cvičíme dvě a půl hodiny a už končíme. Klidně bych pokračoval dál.

### A poznatky:

- Hodně dávají důraz na komunitu - cvičení s lidma. Ideálem je jedna komunita, se kterou cvičíte dlouhodobě a vzájemně si pomáháte ke zlepšení. Tedy opět něco, co pamatuju s tréningů Aikida. Jsou to znalosti, které se musí vstřebávat osobně. *"To, co tady učíme, se nedá naučit z videí na Youtube"*, říkal na lekci hlavní učitel Petr Růžička.

- Zároveň ale zaznělo: *"Sledujte, jak se někdo šikovný hýbe, odkoukejte to a zkuste to napodobovat."* **Zkoumejte pohyb** - to je asi jedna z hlavních věcí, kterou jsem si odnesl. Vlastní výzkum a vlastní pohybová "tvorba".

- Učitel pohybu praxi nevysvětluje, ale "jen" žáka vede k tomu, aby všechno našel sám. Je to pomalejší, ale daleko hodnotnější poznání. Takže jsme hodně experimentovali sami. Opět je to něco podobného, jako u tréningů bojových umění. 

- Hry s tenisovými míčky, prosté házení, ale také práce s rytmem a flow. Super.

- Bolely mě ruce a sedací kosti. Hodně pohybů začínalo v sedě na zemi a moje prdel je nějaká zpohodlnělá.

- Zaznělo také: *"Není to tanec, není to boj, není to sport. Je to pohyb."*

- Zároveň je ale určitá elegance v pohybech žádoucí. A může to být tanec, může to být boj a třeba i sport.

- Půjdu zas.